# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :certificates do
  match(type: "development", app_identifier: ["com.hiddenjester.swatches",
		"com.hiddenjester.swatches.watchkitapp",
		"com.hiddenjester.swatches.watchkitapp.watchkitextension"])

  match(type: "appstore", app_identifier: ["com.hiddenjester.swatches",
		"com.hiddenjester.swatches.watchkitapp",
		"com.hiddenjester.swatches.watchkitapp.watchkitextension"])
end

platform :ios do
  desc "Build a release build"
  lane :release do
  	capture_screenshots
  	build_app(scheme: "Swatches")
  	upload_to_app_store
  end
  
  lane :icons do
	  appicon(
		appicon_devices: [:ipad, :iphone, :ios_marketing, :watch, :watch_marketing],
		appicon_path: "Common/Assets.xcassets"
	  )
	end
end
